image: maven:latest

stages:
  - test
  - build

testmanager:
  stage: test
  script:
    - echo 'Testing manager'
    - src/test/java/org/exemple/CoffeeManagerTester.java

build_prod:
  stage: build
  script: 
    - echo 'Building script to be added'
  only: 
    - main
  artifacts:
    paths:
      - coffeesim_artifact.zip
    expire_in: 1 week



